- name: CISCO NXOS RUN COMMANDS
  hosts: sw_nxos
  gather_facts: false
  ignore_unreachable: yes
  tasks:
    - name: Configure features
      cisco.nxos.nxos_feature:
        feature: "{{ item }}"
        state: enabled
        save_when: modified
        with_items:
         - "ospf"
         - "bgp"
         - "pim"
         - "fabric forwarding"
         - "interface-vlan"
         - "vn-segment-vlan-based"
         - "nv overlay"
    - name: Configure hostname
      cisco.nxos.nxos_config:
        lines: 
          - hostname Nexus-{{ inventory_hostname }}
        save_when: modified
    - name: configurable backup path
      cisco.nxos.nxos_config:
        backup: yes
        backup_options:
          dir_path: /awx-output-folder/nexus-eve-ng/