- name: CISCO NXOS RUN COMMANDS
  hosts: all
  gather_facts: false
  ignore_unreachable: yes
  tasks:
    - name: Configure features
      cisco.nxos.nxos_config:
        lines: 
          - feature ospf
          - feature bgp
          - feature pim
          - feature fabric forwarding
          - feature interface-vlan
          - feature vn-segment-vlan-based
          - feature nv overlay
        save_when: modified
    - name: Configure mgmt interface
      cisco.nxos.nxos_config:
        lines: 
          - ip address dhcp
        parents: interface mgmt0
        save_when: modified
    - name: configurable backup path
      cisco.nxos.nxos_config:
        backup: yes
        backup_options:
          dir_path: /awx-output-folder/nexus-eve-ng/